services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      - BUNNY_AMQP_ADDRESSES=rabbitmq:5672
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=automation
      - POSTGRES_HOST=db
      - POSTGRES_DB=automation_development
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_BUCKET=mybucket
      - INFLUX_ORG=myorg
      - INFLUX_TOKEN=mytoken
      - REDIS_PASSWORD=superpassword
      - REDIS_HOST=redis
      - RAILS_ENV=development
      - BUNDLER_WITHOUT=production
    networks:
      - automation-network
    depends_on:
      - db
      - rabbitmq
      - redis
      - influxdb

  db:
    image: postgres:12.1
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=automation
      - POSTGRES_DB=automation_development
    ports:
      - "3317:5432"
    networks:
      - automation-network

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    networks:
      - automation-network

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=superpassword
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - "6379:6379"
    networks:
      - automation-network

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    volumes:
      - influx-data:/.influxdbv2
    ports:
      - "8086:8086"
    networks:
      - automation-network

  influxdbcli:
    image: quay.io/influxdb/influxdb:v2.0.3
    entrypoint: influx setup --bucket mybucket -t mytoken -o myorg --username=myusername --password=password --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
    networks:
      - automation-network

volumes:
  postgres-data:
  redis-data:
  influx-data:

networks:
  automation-network:
    driver: bridge

